State.insert_all([
  # US States
  { abbr: "AL", name: "Alabama",              data: {} },
  { abbr: "AK", name: "Alaska",               data: {} },
  { abbr: "AZ", name: "Arizona",              data: {} },
  { abbr: "AR", name: "Arkansas",             data: {} },
  { abbr: "CA", name: "California",           data: {} },
  { abbr: "CO", name: "Colorado",             data: {} },
  { abbr: "CT", name: "Connecticut",          data: {} },
  { abbr: "DE", name: "Delaware",             data: {} },
  { abbr: "DC", name: "District of Columbia", data: {} },
  { abbr: "FL", name: "Florida",              data: {} },
  { abbr: "GA", name: "Georgia",              data: {} },
  { abbr: "HI", name: "Hawaii",               data: {} },
  { abbr: "ID", name: "Idaho",                data: {} },
  { abbr: "IL", name: "Illinois",             data: {} },
  { abbr: "IN", name: "Indiana",              data: {} },
  { abbr: "IA", name: "Iowa",                 data: {} },
  { abbr: "KS", name: "Kansas",               data: {} },
  { abbr: "KY", name: "Kentucky",             data: {} },
  { abbr: "LA", name: "Louisiana",            data: {} },
  { abbr: "ME", name: "Maine",                data: {} },
  { abbr: "MD", name: "Maryland",             data: {} },
  { abbr: "MA", name: "Massachusetts",        data: {} },
  { abbr: "MI", name: "Michigan",             data: {} },
  { abbr: "MN", name: "Minnesota",            data: {} },
  { abbr: "MS", name: "Mississippi",          data: {} },
  { abbr: "MO", name: "Missouri",             data: {} },
  { abbr: "MT", name: "Montana",              data: {} },
  { abbr: "NE", name: "Nebraska",             data: {} },
  { abbr: "NV", name: "Nevada",               data: {} },
  { abbr: "NH", name: "New Hampshire",        data: {} },
  { abbr: "NJ", name: "New Jersey",           data: {} },
  { abbr: "NM", name: "New Mexico",           data: {} },
  { abbr: "NY", name: "New York",             data: {} },
  { abbr: "NC", name: "North Carolina",       data: {} },
  { abbr: "ND", name: "North Dakota",         data: {} },
  { abbr: "OH", name: "Ohio",                 data: {} },
  { abbr: "OK", name: "Oklahoma",             data: {} },
  { abbr: "OR", name: "Oregon",               data: {} },
  { abbr: "PA", name: "Pennsylvania",         data: {} },
  { abbr: "RI", name: "Rhode Island",         data: {} },
  { abbr: "SC", name: "South Carolina",       data: {} },
  { abbr: "SD", name: "South Dakota",         data: {} },
  { abbr: "TN", name: "Tennessee",            data: {} },
  { abbr: "TX", name: "Texas",                data: {} },
  { abbr: "UT", name: "Utah",                 data: {} },
  { abbr: "VT", name: "Vermont",              data: {} },
  { abbr: "VA", name: "Virginia",             data: {} },
  { abbr: "WA", name: "Washington",           data: {} },
  { abbr: "WV", name: "West Virginia",        data: {} },
  { abbr: "WI", name: "Wisconsin",            data: {} },
  { abbr: "WY", name: "Wyoming",              data: {} },
  # Military
  { abbr: "AE", name: "Armed Forces Africa",      data: { military: true } },
  { abbr: "AA", name: "Armed Forces Americas",    data: { military: true } },
  { abbr: "AE", name: "Armed Forces Canada",      data: { military: true } },
  { abbr: "AE", name: "Armed Forces Europe",      data: { military: true } },
  { abbr: "AE", name: "Armed Forces Middle East", data: { military: true } },
  { abbr: "AP", name: "Armed Forces Pacific",     data: { military: true } },
])

Rails.logger.info "Seeded States: #{State.count}"
